apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cilikube.fullname" . }}-secrets
  labels:
    {{- include "cilikube.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
