apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cilikube
  namespace: cilikube
  labels:
    app.kubernetes.io/name: cilikube
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: cilikube.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cilikube-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cilikube-frontend
                port:
                  number: 80
