apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cilikube-data
  namespace: cilikube
  labels:
    app.kubernetes.io/name: cilikube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
