apiVersion: v2
name: cilikube
description: CiliKube Kubernetes multi-cluster management platform
type: application
version: 1.0.1
appVersion: "1.0.1"
keywords:
  - kubernetes
  - dashboard
  - multi-cluster
maintainers:
  - name: CiliKube
    url: https://github.com/ciliverse/cilikube
